/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreateLabelFromRateResponseBody = Label;
export type SeId = string;
export type LabelStatus = "processing" | "completed" | "error" | "voided";
export type SeId1 = string;
export type Date = string;
export type DateTime = string;
export type Currency = "usd" | "cad" | "aud" | "gbp" | "eur" | "nzd";
export type Currency1 = "usd" | "cad" | "aud" | "gbp" | "eur" | "nzd";
export type SeId2 = string;
export type SeId3 = string;
export type LabelChargeEvent =
  | "carrier_default"
  | "on_creation"
  | "on_carrier_acceptance";
export type ServiceCode = string;
export type PackageCode = string;
export type DateTime1 = string;
export type LabelFormat = "pdf" | "png" | "zpl";
export type DisplayScheme = "label" | "qr_code";
export type LabelLayout = "4x6" | "letter";
export type ImageId = string;
export type CarrierCode = string;
export type TrackingStatus = "unknown" | "in_transit" | "error" | "delivered";
export type Url = string;
export type Url1 = string;
export type Url2 = string;
export type Url3 = string;
export type Link = OptionalLink;
export type Url4 = string;
export type Link1 = OptionalLink1;
export type Url5 = string;
export type PackageCode1 = string;
export type WeightUnit = "pound" | "ounce" | "gram" | "kilogram";
export type DimensionUnit = "inch" | "centimeter";
export type Currency2 = "usd" | "cad" | "aud" | "gbp" | "eur" | "nzd";
export type TrackingNumber = string;

export interface Label {
  label_id?: SeId;
  status?: LabelStatus;
  shipment_id?: SeId1;
  ship_date?: Date;
  created_at?: DateTime;
  shipment_cost?: MonetaryValue;
  insurance_cost?: MonetaryValue1;
  tracking_number?: string;
  is_return_label?: boolean;
  rma_number?: string;
  is_international?: boolean;
  batch_id?: SeId2;
  carrier_id?: SeId3;
  charge_event?: LabelChargeEvent;
  service_code?: ServiceCode;
  package_code?: PackageCode;
  voided?: boolean;
  voided_at?: DateTime1;
  label_format?: LabelFormat & string;
  display_scheme?: DisplayScheme & string;
  label_layout?: LabelLayout & string;
  trackable?: boolean;
  label_image_id?: ImageId;
  carrier_code?: CarrierCode;
  tracking_status?: TrackingStatus;
  label_download?: LabelDownload;
  form_download?: Link;
  insurance_claim?: Link1;
  packages?: Package[];
}
export interface MonetaryValue {
  currency: Currency;
  amount: number;
}
export interface MonetaryValue1 {
  currency: Currency1;
  amount: number;
}
export interface LabelDownload {
  href?: Url;
  pdf?: Url1;
  png?: Url2;
  zpl?: Url3;
}
export interface OptionalLink {
  href?: Url4;
  type?: string;
}
export interface OptionalLink1 {
  href?: Url5;
  type?: string;
}
export interface Package {
  package_code?: PackageCode1;
  weight: Weight;
  dimensions?: Dimensions;
  insured_value?: MonetaryValue2;
  tracking_number?: TrackingNumber;
  label_messages?: LabelMessages;
  external_package_id?: string;
}
export interface Weight {
  value: number;
  unit: WeightUnit;
}
export interface Dimensions {
  unit: DimensionUnit & string;
  length: number;
  width: number;
  height: number;
}
export interface MonetaryValue2 {
  currency: Currency2;
  amount: number;
}
export interface LabelMessages {
  reference1: string;
  reference2: string;
  reference3: string;
}
