/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type CreateLabelFromRateRequestBody = PurchaseLabelWithoutShipment;
export declare type ValidateAddress = "no_validation" | "validate_only" | "validate_and_clean";
export declare type LabelLayout = "4x6" | "letter";
export declare type LabelFormat = "pdf" | "png" | "zpl";
export declare type LabelDownloadType = "url" | "inline";
export declare type DisplayScheme = "label" | "qr_code";
export interface PurchaseLabelWithoutShipment {
    validate_address?: ValidateAddress;
    label_layout?: LabelLayout & string;
    label_format?: LabelFormat & string;
    label_download_type?: LabelDownloadType;
    display_scheme?: DisplayScheme & string;
}
