/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type CreateLabelFromRateResponseBody = Label;
export declare type SeId = string;
export declare type LabelStatus = "processing" | "completed" | "error" | "voided";
export declare type SeId1 = string;
export declare type Date = string;
export declare type DateTime = string;
export declare type Currency = "usd" | "cad" | "aud" | "gbp" | "eur" | "nzd";
export declare type Currency1 = "usd" | "cad" | "aud" | "gbp" | "eur" | "nzd";
export declare type SeId2 = string;
export declare type SeId3 = string;
export declare type LabelChargeEvent = "carrier_default" | "on_creation" | "on_carrier_acceptance";
export declare type ServiceCode = string;
export declare type PackageCode = string;
export declare type DateTime1 = string;
export declare type LabelFormat = "pdf" | "png" | "zpl";
export declare type DisplayScheme = "label" | "qr_code";
export declare type LabelLayout = "4x6" | "letter";
export declare type ImageId = string;
export declare type CarrierCode = string;
export declare type TrackingStatus = "unknown" | "in_transit" | "error" | "delivered";
export declare type Url = string;
export declare type Url1 = string;
export declare type Url2 = string;
export declare type Url3 = string;
export declare type Link = OptionalLink;
export declare type Url4 = string;
export declare type Link1 = OptionalLink1;
export declare type Url5 = string;
export declare type PackageCode1 = string;
export declare type WeightUnit = "pound" | "ounce" | "gram" | "kilogram";
export declare type DimensionUnit = "inch" | "centimeter";
export declare type Currency2 = "usd" | "cad" | "aud" | "gbp" | "eur" | "nzd";
export declare type TrackingNumber = string;
export interface Label {
    label_id?: SeId;
    status?: LabelStatus;
    shipment_id?: SeId1;
    ship_date?: Date;
    created_at?: DateTime;
    shipment_cost?: MonetaryValue;
    insurance_cost?: MonetaryValue1;
    tracking_number?: string;
    is_return_label?: boolean;
    rma_number?: string;
    is_international?: boolean;
    batch_id?: SeId2;
    carrier_id?: SeId3;
    charge_event?: LabelChargeEvent;
    service_code?: ServiceCode;
    package_code?: PackageCode;
    voided?: boolean;
    voided_at?: DateTime1;
    label_format?: LabelFormat & string;
    display_scheme?: DisplayScheme & string;
    label_layout?: LabelLayout & string;
    trackable?: boolean;
    label_image_id?: ImageId;
    carrier_code?: CarrierCode;
    tracking_status?: TrackingStatus;
    label_download?: LabelDownload;
    form_download?: Link;
    insurance_claim?: Link1;
    packages?: Package[];
}
export interface MonetaryValue {
    currency: Currency;
    amount: number;
}
export interface MonetaryValue1 {
    currency: Currency1;
    amount: number;
}
export interface LabelDownload {
    href?: Url;
    pdf?: Url1;
    png?: Url2;
    zpl?: Url3;
}
export interface OptionalLink {
    href?: Url4;
    type?: string;
}
export interface OptionalLink1 {
    href?: Url5;
    type?: string;
}
export interface Package {
    package_code?: PackageCode1;
    weight: Weight;
    dimensions?: Dimensions;
    insured_value?: MonetaryValue2;
    tracking_number?: TrackingNumber;
    label_messages?: LabelMessages;
    external_package_id?: string;
}
export interface Weight {
    value: number;
    unit: WeightUnit;
}
export interface Dimensions {
    unit: DimensionUnit & string;
    length: number;
    width: number;
    height: number;
}
export interface MonetaryValue2 {
    currency: Currency2;
    amount: number;
}
export interface LabelMessages {
    reference1: string;
    reference2: string;
    reference3: string;
}
